---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
  namespace: kagent-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kagent-crds
      version: "0.6.3"
      sourceRef:
        kind: HelmRepository
        name: kagent-helm-repo
        namespace: kagent-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
