apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 24h
  timeout: 5m
  prune: false  # Don't prune Gateway API CRDs as they might be used by GKE
  wait: true
  sourceRef:
    kind: OCIRepository
    name: gateway-api-crds
  path: ./
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/kubernetes-sigs/gateway-api
  ref:
    tag: v1.4.0
  verify:
    provider: cosign
