apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Team Alpha - Application Team
# Running: whereami application for service location testing

resources:
  - landing-zone.yaml
  - whereami-deployment.yaml
