---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
  namespace: kgateway-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kgateway-crds
      version: "v2.0.4"
      sourceRef:
        kind: HelmRepository
        name: kgateway-helm-repo
        namespace: kgateway-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
