apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Team Bravo - Application Team
# Running: fortio echo server (simulating real-world workload)

resources:
  - fortio-echo-deployment.yaml
